# Generated by Django 6.0.1 on 2026-01-12 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("form_factor", models.CharField(max_length=255, null=True)),
                ("color", models.CharField(max_length=255, null=True)),
                ("psu_wattage", models.PositiveIntegerField(null=True)),
                ("side_panel", models.BooleanField(null=True)),
                ("external_bays", models.PositiveIntegerField(null=True)),
                ("internal_bays", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaseFans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(null=True)),
                ("color", models.CharField(max_length=255, null=True)),
                ("pwm", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("cores", models.PositiveIntegerField(null=True)),
                ("tdp", models.PositiveIntegerField(null=True)),
                ("integrated_graphics", models.CharField(max_length=255, null=True)),
                ("multithreading", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CPUCooler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255, null=True)),
                ("radiator_size", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("chipset", models.CharField(max_length=255, null=True)),
                ("color", models.CharField(max_length=255, null=True)),
                ("length", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("module_type", models.CharField(max_length=255, null=True)),
                ("number_of_modules", models.PositiveIntegerField(null=True)),
                ("color", models.CharField(max_length=255, null=True)),
                ("first_word_latency", models.FloatField(null=True)),
                ("cas_timing", models.PositiveIntegerField(null=True)),
                ("error_correction", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("socket", models.CharField(max_length=255, null=True)),
                ("form_factor", models.CharField(max_length=255, null=True)),
                ("ram_slots", models.PositiveIntegerField(null=True)),
                ("color", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PSU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("form_factor", models.CharField(max_length=255, null=True)),
                ("efficiency_rating", models.CharField(max_length=255, null=True)),
                ("wattage", models.PositiveIntegerField(null=True)),
                ("modular", models.CharField(max_length=255, null=True)),
                ("color", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StorageDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("storage_type", models.CharField(max_length=255, null=True)),
                ("platter_rpm", models.PositiveIntegerField(null=True)),
                ("form_factor", models.CharField(max_length=255, null=True)),
                ("interface", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(max_length=100)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "case",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.case",
                    ),
                ),
                (
                    "fan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.casefans",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="computers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cpu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.cpu",
                    ),
                ),
                (
                    "cpucooler",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.cpucooler",
                    ),
                ),
                (
                    "gpu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.gpu",
                    ),
                ),
                (
                    "memory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.memory",
                    ),
                ),
                (
                    "motherboard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.motherboard",
                    ),
                ),
                (
                    "psu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.psu",
                    ),
                ),
                (
                    "storagedrive",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.storagedrive",
                    ),
                ),
            ],
        ),
    ]
